import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { hasPermission } from "../../auth/utils/permissions";
import { getUrns } from "../../urns/api/urnsApi";
import { getSupplyItems } from "../api/inventoryApi";
import { getBoms, getBomCosts, saveBom } from "../api/bomApi";
import { DecimalInput } from "../../../components/ui/DecimalInput";
const input = "w-full rounded-lg border border-slate-300 px-3 py-2 text-sm";
type Line = { supplyItemId: string; requiredQuantity: string; unitOfMeasure: string };
export function BomPage() {
  const manage = hasPermission("Inventory.Manage"); const canSeeCosts = hasPermission("Purchasing.View"); const [urnId,setUrnId]=useState(""); const [lines,setLines]=useState<Line[]>([]); const qc=useQueryClient();
  const urns=useQuery({queryKey:["urns-bom"],queryFn:()=>getUrns(false)}); const supplies=useQuery({queryKey:["bom-supplies"],queryFn:()=>getSupplyItems("")}); const boms=useQuery({queryKey:["boms",urnId],queryFn:()=>getBoms(urnId),enabled:!!urnId}); const costs=useQuery({queryKey:["bom-costs",urnId],queryFn:()=>getBomCosts(urnId),enabled:!!urnId&&canSeeCosts}); const current=(canSeeCosts?costs.data:boms.data)?.find(x=>x.isActive);
  const mutation=useMutation({mutationFn:()=>saveBom({urnId,items:lines}),onSuccess:()=>{qc.invalidateQueries({queryKey:["boms",urnId]});toast.success("Lista de materiales guardada.");},onError:()=>toast.error("No fue posible guardar la lista.")}); const updateLine=(i:number,v:Partial<Line>)=>setLines(xs=>xs.map((x,j)=>j===i?{...x,...v}:x));
  return <div className="space-y-6"><header><h1 className="text-2xl font-bold">Lista de materiales</h1><p className="text-sm text-slate-500">Requerimientos internos para urnas fabricadas; no descuenta inventario.</p></header><select className={input} value={urnId} onChange={e=>setUrnId(e.target.value)}><option value="">Selecciona una urna</option>{(urns.data??[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{urnId&&<><div className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Materiales</h2>{lines.map((line,index)=><div className="grid gap-2 md:grid-cols-[1fr_150px_150px_auto]" key={index}><select className={input} value={line.supplyItemId} onChange={e=>updateLine(index,{supplyItemId:e.target.value})}><option value="">Insumo</option>{(supplies.data?.items??[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><DecimalInput className={input} value={line.requiredQuantity} onChange={e=>updateLine(index,{requiredQuantity:e.target.value})} placeholder="Cantidad"/><input className={input} value={line.unitOfMeasure} onChange={e=>updateLine(index,{unitOfMeasure:e.target.value})} placeholder="Unidad"/><button type="button" onClick={()=>setLines(xs=>xs.filter((_,i)=>i!==index))}>Quitar</button></div>)}{manage&&<div><button type="button" className="rounded border px-3 py-2" onClick={()=>setLines(xs=>[...xs,{supplyItemId:"",requiredQuantity:"",unitOfMeasure:"g"}])}>Agregar material</button><button type="button" className="ml-2 rounded bg-slate-900 px-3 py-2 text-white" onClick={()=>mutation.mutate()}>Guardar versión</button></div>}</div>{current&&<div className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Versión {current.version}</h2>{current.items.map(x=><div key={x.id} className="flex justify-between border-b py-1 text-sm"><span>{x.supplyItemName}: {x.requiredQuantity} {x.unitOfMeasure}</span>{canSeeCosts&&<span>{x.costAvailable?`${x.estimatedCost} ${x.currency??""}`:"Costo no disponible"}</span>}</div>)}{canSeeCosts&&<div className="mt-3 font-semibold">Costo estimado: {current.estimatedMaterialCost??"No disponible"} {current.currency??""}</div>}</div>}</>}</div>;
}
