import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { hasPermission } from "../../auth/utils/permissions";
import { getUrns } from "../../urns/api/urnsApi";
import { getBoms } from "../api/bomApi";
import { createProduction, getProductions, getProductionCosts } from "../api/productionApi";
import { DecimalInput } from "../../../components/ui/DecimalInput";
const input="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm";
export function ProductionPage(){const manage=hasPermission("Inventory.Manage"),costs=hasPermission("Purchasing.View");const[urnId,setUrnId]=useState("");const[bomId,setBomId]=useState("");const[actual,setActual]=useState<Record<string,string>>({});const[quantity,setQuantity]=useState("1");const qc=useQueryClient();const urns=useQuery({queryKey:["production-urns"],queryFn:()=>getUrns(false)});const boms=useQuery({queryKey:["production-boms",urnId],queryFn:()=>getBoms(urnId),enabled:!!urnId});const history=useQuery({queryKey:["productions"],queryFn:costs?getProductionCosts:getProductions});const bom=boms.data?.find(x=>x.isActive);const mutation=useMutation({mutationFn:()=>createProduction({urnId,urnBillOfMaterialsId:bomId||bom?.id,quantityProduced:quantity,usages:(bom?.items??[]).map(x=>({supplyItemId:x.supplyItemId,actualQuantity:actual[x.supplyItemId]??"0",wasteQuantity:null}))}),onSuccess:()=>{qc.invalidateQueries({queryKey:["productions"]});toast.success("Producción registrada.");},onError:(e:any)=>toast.error(e?.response?.data?.message??"No fue posible registrar la producción.")});return <div className="space-y-6"><header><h1 className="text-2xl font-bold">Producción de urnas</h1><p className="text-sm text-slate-500">El consumo se registra contra la BOM seleccionada y descuenta materiales reales.</p></header><select className={input} value={urnId} onChange={e=>{setUrnId(e.target.value);setBomId("")}}><option value="">Selecciona una urna</option>{(urns.data??[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{bom&&<><div className="rounded-xl border bg-white p-4 space-y-3"><div className="font-semibold">BOM versión {bom.version}</div><DecimalInput className={input} value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Cantidad producida" />{bom.items.map(x=><div className="grid grid-cols-2 gap-3 text-sm" key={x.id}><span>{x.supplyItemName} · esperado {x.requiredQuantity} {x.unitOfMeasure}</span>{manage&&<DecimalInput className={input} value={actual[x.supplyItemId]??String(x.requiredQuantity)} onChange={e=>setActual({...actual,[x.supplyItemId]:e.target.value})} placeholder="Utilizado" />}</div>)}{manage&&<button className="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white" onClick={()=>mutation.mutate()}>Registrar producción</button>}</div></>}{<div className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Historial</h2>{(history.data??[]).map(x=><div className="border-b py-2 text-sm" key={x.id}><div>{x.urnName} · {x.quantityProduced} unidad(es) · BOM v{x.bomVersion}</div>{costs&&<div>{x.costComplete?`Costo: ${x.totalMaterialCost??""}`:"Costo no disponible"}</div>}</div>)}</div>}</div>}
