import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { ScanCodeScanner } from "../../../components/scanner/ScanCodeScanner";
import { DecimalInput } from "../../../components/ui/DecimalInput";
import { getSupplyItemByScan, recordInventoryMovement, recordStockCount } from "../api/inventoryApi";
import { getLotByScan } from "../api/lotsApi";
import { hasPermission } from "../../auth/utils/permissions";

export function ScannerPage() {
  const manage = hasPermission("Inventory.Manage"); const [code,setCode]=useState(""); const [qty,setQty]=useState(""); const [type,setType]=useState("Consumption"); const [count,setCount]=useState("");
  const result=useQuery({queryKey:["scanner",code],queryFn:async()=>{try{return {kind:"Insumo",data:await getSupplyItemByScan(code)}}catch{return {kind:"Lote/Bobina",data:await getLotByScan(code)}}},enabled:!!code});
  const item:any=result.data?.data; const stock=item?.currentQuantity??item?.remainingQuantity; const id=item?.supplyItemId??item?.id; const lot=result.data?.kind==="Lote/Bobina"?item?.id:null;
  const movement=useMutation({mutationFn:recordInventoryMovement,onSuccess:()=>{toast.success("Operación completada.");setQty("")},onError:(e:any)=>toast.error(e?.response?.data?.message??"Operación rechazada.")});
  const counting=useMutation({mutationFn:recordStockCount,onSuccess:(x:any)=>{toast.success(`Conteo confirmado. Variación: ${x.variance}`);setCount("")},onError:(e:any)=>toast.error(e?.response?.data?.message??"No fue posible confirmar el conteo.")});
  return <main className="mx-auto max-w-2xl space-y-5"><h1 className="text-2xl font-bold">Escáner de inventario</h1><p className="text-sm text-slate-500">Escanea o escribe un ScanCode. La cámara usa los códigos de las etiquetas existentes.</p><ScanCodeScanner onCode={setCode}/>{result.isFetching&&<p>Resolviendo código…</p>}{result.isError&&<p className="rounded border border-amber-200 bg-amber-50 p-4">Código no encontrado.</p>}{item&&<section className="space-y-4 rounded-xl border bg-white p-4"><h2 className="text-lg font-semibold">{item.name??item.supplyItemName}</h2><p className="text-sm">Tipo: {result.data?.kind} · Código: {item.scanCode} · Existencia: {stock} {item.unitOfMeasure}</p>{manage&&<><div className="grid gap-2 sm:grid-cols-2"><select className="rounded border px-3 py-2" value={type} onChange={e=>setType(e.target.value)}><option value="Consumption">Consumo</option><option value="Waste">Merma</option><option value="ManualAdjustmentIncrease">Ajuste positivo</option><option value="ManualAdjustmentDecrease">Ajuste negativo</option></select><DecimalInput className="rounded border px-3 py-2" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Cantidad"/></div><button className="rounded bg-slate-900 px-4 py-2 text-white" disabled={!qty||Number(qty)<=0||movement.isPending} onClick={()=>movement.mutate({supplyItemId:id,lotId:lot,movementType:type,quantity:qty})}>Confirmar operación</button><div className="border-t pt-3"><h3 className="font-medium">Conteo físico</h3><p className="text-sm text-slate-500">Sistema actual: {stock} {item.unitOfMeasure}. El servidor valida que no haya cambiado.</p><DecimalInput className="mt-2 rounded border px-3 py-2" value={count} onChange={e=>setCount(e.target.value)} placeholder="Cantidad contada"/><button className="ml-2 rounded border px-4 py-2" disabled={!count||Number(count)<0||counting.isPending} onClick={()=>counting.mutate({supplyItemId:id,lotId:lot,countedQuantity:count,expectedSystemQuantity:stock})}>Confirmar conteo</button></div></>}</section>}</main>;
}
