import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { hasPermission } from "../../auth/utils/permissions";
import { getSpendingReport } from "../api/inventoryApi";

const money = (amount: number, currency: string) => new Intl.NumberFormat("es-MX", { style: "currency", currency, minimumFractionDigits: 2 }).format(amount);
const iso = (date: Date) => date.toISOString().slice(0, 10);
function monthStart(offset = 0) { const date = new Date(); return iso(new Date(date.getFullYear(), date.getMonth() + offset, 1)); }
function monthEnd(offset = 0) { const date = new Date(); return iso(new Date(date.getFullYear(), date.getMonth() + offset + 1, 0)); }

export function SpendingReportsPage() {
  const finance = hasPermission("Finance.View");
  const purchasing = hasPermission("Purchasing.View");
  const [startDate, setStartDate] = useState(monthStart());
  const [endDate, setEndDate] = useState(monthEnd());
  const report = useQuery({ queryKey: ["spending-report", startDate, endDate], queryFn: () => getSpendingReport({ startDate, endDate }), enabled: finance || purchasing });
  const title = finance && purchasing ? "Reportes de gastos" : finance ? "Reporte de gastos operativos" : "Reporte de compras";
  const monthly = useMemo(() => report.data?.monthlyTrend ?? [], [report.data]);
  function preset(kind: "current" | "previous" | "30" | "year") { const today = new Date(); if (kind === "current") { setStartDate(monthStart()); setEndDate(monthEnd()); } if (kind === "previous") { setStartDate(monthStart(-1)); setEndDate(monthEnd(-1)); } if (kind === "30") { const start = new Date(); start.setDate(today.getDate() - 29); setStartDate(iso(start)); setEndDate(iso(today)); } if (kind === "year") { setStartDate(`${today.getFullYear()}-01-01`); setEndDate(`${today.getFullYear()}-12-31`); } }
  return <div className="space-y-6">
    <header><h1 className="text-2xl font-bold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">Gastos operativos y compras se muestran por separado y nunca se convierten entre monedas.</p></header>
    <section className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4"><label className="text-sm">Periodo<input className="mt-1 block rounded border px-3 py-2" type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label className="text-sm">a<input className="mt-1 block rounded border px-3 py-2" type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label><button className="rounded border px-3 py-2 text-sm" onClick={() => preset("current")}>Este mes</button><button className="rounded border px-3 py-2 text-sm" onClick={() => preset("previous")}>Mes anterior</button><button className="rounded border px-3 py-2 text-sm" onClick={() => preset("30")}>Últimos 30 días</button><button className="rounded border px-3 py-2 text-sm" onClick={() => preset("year")}>Este año</button></section>
    {report.isError && <p className="rounded border border-red-200 bg-red-50 p-4 text-red-700">No fue posible cargar el reporte.</p>}
    <section className="grid gap-4 md:grid-cols-3">{(report.data?.summary ?? []).map((item) => <div key={item.currency} className="rounded-xl border bg-white p-4"><p className="text-sm text-slate-500">{item.currency}</p>{finance && <p className="mt-2">Gastos operativos: <strong>{money(item.operatingExpenses, item.currency)}</strong> ({item.expenseCount})</p>}{purchasing && <p className="mt-2">Compras: <strong>{money(item.purchases, item.currency)}</strong> ({item.purchaseCount})</p>}{finance && purchasing && <p className="mt-2 text-lg">Total: <strong>{money(item.total, item.currency)}</strong></p>}</div>)}</section>
    {finance && <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Por categoría</h2><table className="mt-3 w-full text-sm"><thead><tr className="text-left text-slate-500"><th>Categoría</th><th>Moneda</th><th>Total</th><th>Gastos</th><th>% operativo</th></tr></thead><tbody>{(report.data?.expenseCategories ?? []).map((row) => <tr key={`${row.categoryId}-${row.currency}`} className="border-t"><td>{row.categoryName}</td><td>{row.currency}</td><td>{money(row.total, row.currency)}</td><td>{row.expenseCount}</td><td>{row.percentage}%</td></tr>)}</tbody></table></section>}
    {purchasing && <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Compras por proveedor</h2><table className="mt-3 w-full text-sm"><thead><tr className="text-left text-slate-500"><th>Proveedor</th><th>Moneda</th><th>Total recibido</th><th>Compras</th><th>% compras</th></tr></thead><tbody>{(report.data?.purchaseSuppliers ?? []).map((row, index) => <tr key={`${row.supplierId ?? index}-${row.currency}`} className="border-t"><td>{row.supplierName}</td><td>{row.currency}</td><td>{money(row.total, row.currency)}</td><td>{row.purchaseCount}</td><td>{row.percentage}%</td></tr>)}</tbody></table></section>}
    {finance && (report.data?.expenseSuppliers.length ?? 0) > 0 && <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Gastos operativos por proveedor</h2><table className="mt-3 w-full text-sm"><thead><tr className="text-left text-slate-500"><th>Proveedor</th><th>Moneda</th><th>Total</th><th>Gastos</th></tr></thead><tbody>{(report.data?.expenseSuppliers ?? []).map((row, index) => <tr key={`${row.supplierId ?? index}-${row.currency}`} className="border-t"><td>{row.supplierName}</td><td>{row.currency}</td><td>{money(row.total, row.currency)}</td><td>{row.purchaseCount}</td></tr>)}</tbody></table></section>}
    <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Tendencia mensual</h2><table className="mt-3 w-full text-sm"><thead><tr className="text-left text-slate-500"><th>Mes</th><th>Moneda</th>{finance && <th>Gastos operativos</th>}{purchasing && <th>Compras</th>}{finance && purchasing && <th>Total</th>}</tr></thead><tbody>{monthly.map((row) => <tr key={`${row.month}-${row.currency}`} className="border-t"><td>{new Date(row.month).toLocaleDateString("es-MX", { month: "long", year: "numeric" })}</td><td>{row.currency}</td>{finance && <td>{money(row.operatingExpenses, row.currency)}</td>}{purchasing && <td>{money(row.purchases, row.currency)}</td>}{finance && purchasing && <td>{money(row.total, row.currency)}</td>}</tr>)}</tbody></table></section>
    {report.data && <p className="text-xs text-slate-500">Base de compras: {report.data.purchaseAmountBasis}</p>}
  </div>;
}
