import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { hasPermission } from "../../auth/utils/permissions";
import { getUrns } from "../../urns/api/urnsApi";
import { getSupplyItems } from "../api/inventoryApi";
import { getUrnInventory, getUrnMovements, saveUrnInventory } from "../api/urnInventoryApi";
const input="w-full rounded border border-slate-300 px-3 py-2 text-sm";
const typeLabel=(x:string)=>({PurchaseReceipt:"Entrada por compra",ManufacturingReceipt:"Entrada por producción",ManualAdjustmentIncrease:"Ajuste positivo",ManualAdjustmentDecrease:"Ajuste negativo",Consumption:"Consumo",Waste:"Merma"}[x]??x);
export function UrnInventoryPage(){const manage=hasPermission("Inventory.Manage");const[urnId,setUrnId]=useState("");const[itemId,setItemId]=useState("");const[selectedId,setSelectedId]=useState<string|null>(null);const qc=useQueryClient();const rows=useQuery({queryKey:["urn-inventory"],queryFn:getUrnInventory});const urns=useQuery({queryKey:["urns-inventory"],queryFn:()=>getUrns(false)});const items=useQuery({queryKey:["finished-items"],queryFn:()=>getSupplyItems("")});const movements=useQuery({queryKey:["urn-movements",selectedId],queryFn:()=>getUrnMovements(selectedId!),enabled:!!selectedId});const save=useMutation({mutationFn:()=>saveUrnInventory({urnId,supplyItemId:itemId}),onSuccess:()=>{qc.invalidateQueries({queryKey:["urn-inventory"]});setUrnId("");setItemId("");toast.success("Vinculación guardada.")},onError:(e:any)=>toast.error(e?.response?.data?.message??"No fue posible vincular.")});return <div className="space-y-6"><header><h1 className="text-2xl font-bold">Inventario de urnas</h1><p className="text-sm text-slate-500">Existencias y movimientos derivados del ledger de insumos terminados.</p></header>{manage&&<div className="grid gap-2 rounded-xl border bg-white p-4 md:grid-cols-3"><select className={input} value={urnId} onChange={e=>setUrnId(e.target.value)}><option value="">Urna</option>{(urns.data??[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={input} value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">Insumo terminado</option>{(items.data?.items??[]).map(x=><option key={x.id} value={x.id}>{x.name} · {x.unitOfMeasure}</option>)}</select><button className="rounded bg-slate-900 px-3 py-2 text-white" disabled={!urnId||!itemId} onClick={()=>save.mutate()}>Vincular</button></div>}<div className="rounded-xl border bg-white divide-y">{(rows.data??[]).map(x=><div className="p-4" key={x.id}><button type="button" className="w-full text-left" onClick={()=>setSelectedId(x.supplyItemId)}><div className="font-medium">{x.urnName}</div><div className="text-sm">Insumo vinculado: {x.supplyItemName} · Código: {x.scanCode}</div><div className={x.isLowStock?"font-semibold text-red-600":""}>Existencia: {x.currentQuantity} {x.unitOfMeasure} · Mínimo: {x.minimumQuantity}{x.isLowStock?" · Bajo mínimo":""}</div></button>{selectedId===x.supplyItemId&&<div className="mt-3 border-t pt-3"><h2 className="font-semibold">Historial de movimientos</h2>{(movements.data??[]).map(m=><div className="border-b py-2 text-sm" key={m.id}><div>{new Date(m.occurredAt).toLocaleString("es-MX")} · {typeLabel(m.movementType)} · {m.quantity} {m.unitOfMeasure}</div><div className="text-slate-500">Referencia: {m.reference??"—"} · {m.notes??""}</div></div>)}</div>}</div>)}</div></div>}
