import { useEffect, useRef, useState } from "react";

declare global { interface Window { BarcodeDetector?: new (options?: { formats?: string[] }) => { detect(video: HTMLVideoElement): Promise<Array<{ rawValue: string }>> }; } }
export function ScanCodeScanner({ onCode }: { onCode: (code: string) => void }) {
  const [value, setValue] = useState(""); const [camera, setCamera] = useState(false); const [error, setError] = useState(""); const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null); const last = useRef({ code: "", at: 0 });
  useEffect(() => () => stream.current?.getTracks().forEach(track => track.stop()), []);
  useEffect(() => { if (!camera) return; if (!window.BarcodeDetector || !navigator.mediaDevices?.getUserMedia) { setError("La cámara no está disponible en este navegador."); setCamera(false); return; } let active=true; navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } } }).then(s => { stream.current=s; if (video.current) { video.current.srcObject=s; void video.current.play(); } const detector=new window.BarcodeDetector!({formats:["qr_code","code_128","code_39","ean_13","ean_8"]}); const loop=async()=>{if(!active||!video.current)return; try { const codes=await detector.detect(video.current); const code=codes[0]?.rawValue?.trim(); if(code&& (code!==last.current.code||Date.now()-last.current.at>1500)){last.current={code,at:Date.now()};onCode(code);} } catch { setError("No fue posible leer el código."); } if(active) window.setTimeout(loop,250);}; void loop(); }).catch(()=>{setError("Permiso de cámara denegado o cámara no disponible.");setCamera(false);}); return()=>{active=false;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;}; }, [camera,onCode]);
  function submit(e: React.FormEvent) { e.preventDefault(); const code=value.trim(); if(code){onCode(code);setValue("");} }
  return <div className="space-y-3 rounded-xl border bg-white p-4"><form className="flex gap-2" onSubmit={submit}><input autoFocus className="min-w-0 flex-1 rounded border px-3 py-2" value={value} onChange={e=>setValue(e.target.value)} placeholder="Escanear o escribir ScanCode y presionar Enter"/><button className="rounded bg-slate-900 px-4 py-2 text-sm text-white">Resolver</button></form><button type="button" className="rounded border px-3 py-2 text-sm" onClick={()=>{setError("");setCamera(x=>!x);}}>{camera?"Detener cámara":"Iniciar cámara"}</button>{camera&&<video ref={video} className="max-h-72 w-full rounded-lg bg-black object-contain" muted playsInline />}{error&&<p className="text-sm text-red-700">{error}</p>}</div>;
}
