using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using pcms.Application.Purchasing.DTOs; using pcms.Application.Purchasing.Interfaces; using System.Security.Claims;
namespace pcms.Api.Controllers;
[ApiController,Route("api/purchasing")]
public class PurchasingController(ISupplierSupplyItemService sourcing,IPurchaseService purchases):ControllerBase
{
 [HttpGet("sources"),Authorize(Policy="Purchasing.View")] public async Task<ActionResult<IEnumerable<SupplierSupplyItemDto>>>Sources(Guid? supplierId=null,Guid? supplyItemId=null,bool isActive=true)=>Ok(await sourcing.GetAllAsync(supplierId,supplyItemId,isActive));
 [HttpGet("sources/{id:guid}/history"),Authorize(Policy="Purchasing.View")] public async Task<ActionResult<IEnumerable<CostHistoryDto>>>History(Guid id)=>Ok(await sourcing.GetHistoryAsync(id));
 [HttpPost("sources"),Authorize(Policy="Purchasing.Manage")] public async Task<ActionResult<SupplierSupplyItemDto>>CreateSource(SupplierSupplyItemInput input){try{return Ok(await sourcing.CreateAsync(input));}catch(Exception e)when(e is ArgumentException or InvalidOperationException){return BadRequest(new{message=e.Message});}}
 [HttpPut("sources/{id:guid}"),Authorize(Policy="Purchasing.Manage")] public async Task<ActionResult<SupplierSupplyItemDto>>UpdateSource(Guid id,SupplierSupplyItemInput input){try{return (await sourcing.UpdateAsync(id,input)) is { } x?Ok(x):NotFound();}catch(Exception e)when(e is ArgumentException or InvalidOperationException){return BadRequest(new{message=e.Message});}}
 [HttpDelete("sources/{id:guid}"),Authorize(Policy="Purchasing.Manage")] public async Task<IActionResult>DeactivateSource(Guid id)=>await sourcing.DeactivateAsync(id)?NoContent():NotFound();
 [HttpGet("purchases"),Authorize(Policy="Purchasing.View")] public async Task<ActionResult<PagedPurchasesDto>>Purchases(int page=1,int pageSize=20,DateTime?from=null,DateTime?to=null,Guid? supplierId=null)=>Ok(await purchases.GetAllAsync(page,pageSize,from,to,supplierId));
 [HttpGet("purchases/{id:guid}"),Authorize(Policy="Purchasing.View")] public async Task<ActionResult<PurchaseDto>>Purchase(Guid id)=>(await purchases.GetByIdAsync(id)) is { } x?Ok(x):NotFound();
 [HttpPost("purchases"),Authorize(Policy="Purchasing.Manage")] public async Task<ActionResult<PurchaseDto>>CreatePurchase(PurchaseInput input){try{Guid? user=Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:null;var x=await purchases.CreateAsync(input,user);return CreatedAtAction(nameof(Purchase),new{id=x.Id},x);}catch(ArgumentException e){return BadRequest(new{message=e.Message});}}
 [HttpPut("purchases/{id:guid}"),Authorize(Policy="Purchasing.Manage")] public async Task<ActionResult<PurchaseDto>>UpdatePurchase(Guid id,PurchaseInput input){try{return(await purchases.UpdateDraftAsync(id,input))is { }x?Ok(x):NotFound();}catch(Exception e)when(e is ArgumentException or InvalidOperationException){return BadRequest(new{message=e.Message});}}
 [HttpPost("purchases/{id:guid}/status"),Authorize(Policy="Purchasing.Manage")] public async Task<ActionResult<PurchaseDto>>ChangeStatus(Guid id,[FromBody]pcms.Domain.Enums.PurchaseStatus status){try{return(await purchases.ChangeStatusAsync(id,status))is { }x?Ok(x):NotFound();}catch(InvalidOperationException e){return BadRequest(new{message=e.Message});}}
 [HttpPost("purchases/{id:guid}/receipts"),Authorize(Policy="Purchasing.Manage")] public async Task<ActionResult<PurchaseDto>>Receive(Guid id,ReceiptInput input){try{Guid? user=Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var userId)?userId:null;return Ok(await purchases.ReceiveAsync(id,input,user));}catch(Exception e)when(e is ArgumentException or InvalidOperationException){return BadRequest(new{message=e.Message});}}
}
