// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pcms.Infrastructure.Persistence;

#nullable disable

namespace pcms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817192951_AddCremationQuoteSnapshot")]
    partial class AddCremationQuoteSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pcms.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<decimal?>("ApproximateWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PesoAproximadoKg");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCancelacion");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRecoleccion");

                    b.Property<Guid>("CollectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecolectadoPorUsuarioId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<bool>("HasPersonalBelongings")
                        .HasColumnType("boolean")
                        .HasColumnName("TieneObjetosPersonales");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("TipoUbicacion");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Notas");

                    b.Property<string>("PersonalBelongingsDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DescripcionObjetosPersonales");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("MascotaId");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DireccionRecoleccion");

                    b.Property<string>("PickupContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NombreContactoRecoleccion");

                    b.Property<string>("PickupContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("TelefonoContactoRecoleccion");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CodigoQr");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRecepcionInstalaciones");

                    b.Property<Guid?>("ReferringVeterinarianId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinarioReferenteId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Estado");

                    b.Property<Guid?>("VeterinaryClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinariaId");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt");

                    b.HasIndex("CollectedByUserId");

                    b.HasIndex("PetId");

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.HasIndex("ReferringVeterinarianId");

                    b.HasIndex("Status");

                    b.HasIndex("VeterinaryClinicId");

                    b.ToTable("Recolecciones", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Cremation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("AccessoryDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DescripcionAccesorio");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("AsignadoAUsuarioId");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFinalizacion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<Guid?>("CremationPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("PaqueteCremacionId");

                    b.Property<int>("CremationType")
                        .HasColumnType("integer")
                        .HasColumnName("TipoCremacion");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaEntrega");

                    b.Property<bool>("IncludesCertificate")
                        .HasColumnType("boolean")
                        .HasColumnName("IncluyeCertificado");

                    b.Property<bool>("IncludesPawPrint")
                        .HasColumnType("boolean")
                        .HasColumnName("IncluyeHuella");

                    b.Property<bool>("IncludesUrn")
                        .HasColumnType("boolean")
                        .HasColumnName("IncluyeUrna");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Notas");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NombrePaquete");

                    b.Property<decimal?>("QuotedMaximumWeightKg")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PesoMaximoCotizadoKg");

                    b.Property<decimal?>("QuotedMinimumWeightKg")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PesoMinimoCotizadoKg");

                    b.Property<decimal?>("QuotedPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("PrecioCotizado");

                    b.Property<decimal?>("QuotedWeightKg")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PesoCotizadoKg");

                    b.Property<DateTime?>("ReadyForDeliveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaListaParaEntrega");

                    b.Property<Guid>("ReceptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecepcionId");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaProgramada");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("InstruccionesEspeciales");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInicio");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Estado");

                    b.Property<string>("UrnDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DescripcionUrna");

                    b.Property<Guid?>("UrnId")
                        .HasColumnType("uuid")
                        .HasColumnName("UrnaId");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CremationPackageId");

                    b.HasIndex("ReceptionId")
                        .IsUnique();

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.HasIndex("UrnId");

                    b.ToTable("Cremaciones", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.CremationPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("AccessoryDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DescripcionAccesorio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Descripcion");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("OrdenVisualizacion");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("UrlImagen");

                    b.Property<bool>("IncludesCertificate")
                        .HasColumnType("boolean")
                        .HasColumnName("IncluyeCertificado");

                    b.Property<bool>("IncludesPawPrint")
                        .HasColumnType("boolean")
                        .HasColumnName("IncluyeHuella");

                    b.Property<bool>("IncludesUrn")
                        .HasColumnType("boolean")
                        .HasColumnName("IncluyeUrna");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("EsPublico");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nombre");

                    b.Property<int>("PackageType")
                        .HasColumnType("integer")
                        .HasColumnName("TipoPaquete");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("DescripcionCorta");

                    b.Property<int?>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("Nivel");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsPublic");

                    b.HasIndex("Name");

                    b.ToTable("PaquetesCremacion", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.CremationPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<Guid>("CremationPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("PaqueteCremacionId");

                    b.Property<int>("CremationType")
                        .HasColumnType("integer")
                        .HasColumnName("TipoCremacion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("EsPublico");

                    b.Property<decimal>("MaximumWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PesoMaximoKg");

                    b.Property<decimal>("MinimumWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PesoMinimoKg");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("Precio");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("CremationPackageId", "CremationType", "MinimumWeightKg", "MaximumWeightKg")
                        .IsUnique();

                    b.ToTable("PreciosCremacion", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.CremationPricingConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("AllowIndividualNoAshes")
                        .HasColumnType("boolean")
                        .HasColumnName("PermitirIndividualSinCenizas");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizacion");

                    b.Property<int>("WeightInterval")
                        .HasColumnType("integer")
                        .HasColumnName("IntervaloPesoKg");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionPreciosCremacion", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CorreoElectronico");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ApellidoPaterno");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Telefono");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("text")
                        .HasColumnName("ApellidoMaterno");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("Monto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("MetodoPago");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Notas");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaPago");

                    b.Property<Guid>("PaymentAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("CuentaPagoId");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("RegistradoPorUsuarioId");

                    b.Property<string>("Reference")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Referencia");

                    b.HasKey("Id");

                    b.HasIndex("PaidAt");

                    b.HasIndex("PaymentAccountId");

                    b.HasIndex("RecordedByUserId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.PaymentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<Guid>("CremationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CremacionId");

                    b.Property<decimal>("ServiceTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("TotalServicio");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id");

                    b.HasIndex("CremationId")
                        .IsUnique();

                    b.ToTable("CuentasPago", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("EdadAnios");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Raza");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfDeath")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFallecimiento");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Sexo");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Especie");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("PesoKg");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Mascotas", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Reception", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecoleccionId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<bool>("HasPersonalBelongings")
                        .HasColumnType("boolean")
                        .HasColumnName("TieneObjetosPersonales");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Notas");

                    b.Property<string>("PersonalBelongingsDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DescripcionObjetosPersonales");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("MascotaId");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CodigoQr");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRecepcion");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecibidoPorUsuarioId");

                    b.Property<string>("ReferralNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("NotasReferencia");

                    b.Property<Guid?>("ReferringVeterinarianId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinarioReferenteId");

                    b.Property<decimal>("VerifiedWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PesoVerificadoKg");

                    b.Property<Guid?>("VeterinaryClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinariaId");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .IsUnique();

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("ReferringVeterinarianId");

                    b.HasIndex("VeterinaryClinicId");

                    b.ToTable("Recepciones", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.ReceptionPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TipoContenido");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Notas");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("NombreArchivoOriginal");

                    b.Property<int>("PhotoType")
                        .HasColumnType("integer")
                        .HasColumnName("TipoFoto");

                    b.Property<Guid>("ReceptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecepcionId");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("RutaAlmacenamiento");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("NombreArchivoGuardado");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaSubida");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("SubidoPorUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("FotosRecepcion", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Usuario"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Finanzas"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Ventas"
                        });
                });

            modelBuilder.Entity("pcms.Domain.Entities.Urn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Descripcion");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("OrdenVisualizacion");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("UrlImagen");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("Publico");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Material");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("Precio");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizacion");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsPublic");

                    b.HasIndex("Name");

                    b.ToTable("Urnas", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CorreoElectronico");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Apellido");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("HashContrasena");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Veterinarian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ApellidoPaterno");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Telefono");

                    b.Property<string>("ProfessionalLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CedulaProfesional");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("text")
                        .HasColumnName("ApellidoMaterno");

                    b.Property<Guid?>("VeterinaryClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinariaId");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ProfessionalLicenseNumber");

                    b.HasIndex("VeterinaryClinicId");

                    b.ToTable("Veterinarios", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.VeterinaryClinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Direccion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Telefono");

                    b.Property<string>("PrimaryContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NombreContactoPrincipal");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Name");

                    b.ToTable("Veterinarias", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.VeterinaryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("EdadAnios");

                    b.Property<decimal>("ApproximateWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PesoAproximadoKg");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Raza");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Color");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaConversion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime>("DateOfDeath")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFallecimiento");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("NotasInternas");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CorreoPropietario");

                    b.Property<string>("OwnerFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NombrePropietario");

                    b.Property<string>("OwnerLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ApellidoPaternoPropietario");

                    b.Property<string>("OwnerPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("TelefonoPropietario");

                    b.Property<string>("OwnerSecondLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ApellidoMaternoPropietario");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NombreMascota");

                    b.Property<Guid?>("ReceptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecepcionId");

                    b.Property<Guid?>("ReferringVeterinarianId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinarioReferenteId");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("MotivoRechazo");

                    b.Property<string>("RequestNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("NotasSolicitud");

                    b.Property<int?>("RequestedCremationType")
                        .HasColumnType("integer")
                        .HasColumnName("TipoCremacionSolicitado");

                    b.Property<string>("RequestedPackageName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NombrePaqueteSolicitado");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRevision");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("RevisadoPorUsuarioId");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Sexo");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Especie");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaSolicitud");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("RegistradoPorUsuarioId");

                    b.Property<Guid?>("VeterinaryClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinariaId");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId")
                        .IsUnique();

                    b.HasIndex("ReferringVeterinarianId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("VeterinaryClinicId");

                    b.ToTable("SolicitudesVeterinarias", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Collection", b =>
                {
                    b.HasOne("pcms.Domain.Entities.User", "CollectedByUser")
                        .WithMany()
                        .HasForeignKey("CollectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.Pet", "Pet")
                        .WithMany("Collections")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.Veterinarian", "ReferringVeterinarian")
                        .WithMany()
                        .HasForeignKey("ReferringVeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.VeterinaryClinic", "VeterinaryClinic")
                        .WithMany()
                        .HasForeignKey("VeterinaryClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CollectedByUser");

                    b.Navigation("Pet");

                    b.Navigation("ReferringVeterinarian");

                    b.Navigation("VeterinaryClinic");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Cremation", b =>
                {
                    b.HasOne("pcms.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.CremationPackage", "CremationPackage")
                        .WithMany("Cremations")
                        .HasForeignKey("CremationPackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.Reception", "Reception")
                        .WithOne("Cremation")
                        .HasForeignKey("pcms.Domain.Entities.Cremation", "ReceptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.Urn", "Urn")
                        .WithMany("Cremations")
                        .HasForeignKey("UrnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedToUser");

                    b.Navigation("CremationPackage");

                    b.Navigation("Reception");

                    b.Navigation("Urn");
                });

            modelBuilder.Entity("pcms.Domain.Entities.CremationPrice", b =>
                {
                    b.HasOne("pcms.Domain.Entities.CremationPackage", "CremationPackage")
                        .WithMany("Prices")
                        .HasForeignKey("CremationPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CremationPackage");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Payment", b =>
                {
                    b.HasOne("pcms.Domain.Entities.PaymentAccount", "PaymentAccount")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentAccount");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("pcms.Domain.Entities.PaymentAccount", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Cremation", "Cremation")
                        .WithOne("PaymentAccount")
                        .HasForeignKey("pcms.Domain.Entities.PaymentAccount", "CremationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cremation");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Pet", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Customer", "Customer")
                        .WithMany("Pets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Reception", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Collection", "Collection")
                        .WithOne("Reception")
                        .HasForeignKey("pcms.Domain.Entities.Reception", "CollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.Pet", "Pet")
                        .WithOne("Reception")
                        .HasForeignKey("pcms.Domain.Entities.Reception", "PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.Veterinarian", "ReferringVeterinarian")
                        .WithMany("ReferredReceptions")
                        .HasForeignKey("ReferringVeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.VeterinaryClinic", "VeterinaryClinic")
                        .WithMany("ReferredReceptions")
                        .HasForeignKey("VeterinaryClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Collection");

                    b.Navigation("Pet");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("ReferringVeterinarian");

                    b.Navigation("VeterinaryClinic");
                });

            modelBuilder.Entity("pcms.Domain.Entities.ReceptionPhoto", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Reception", "Reception")
                        .WithMany("Photos")
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reception");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("pcms.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Veterinarian", b =>
                {
                    b.HasOne("pcms.Domain.Entities.VeterinaryClinic", "VeterinaryClinic")
                        .WithMany("Veterinarians")
                        .HasForeignKey("VeterinaryClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("VeterinaryClinic");
                });

            modelBuilder.Entity("pcms.Domain.Entities.VeterinaryRequest", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Reception", "Reception")
                        .WithOne()
                        .HasForeignKey("pcms.Domain.Entities.VeterinaryRequest", "ReceptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.Veterinarian", "ReferringVeterinarian")
                        .WithMany()
                        .HasForeignKey("ReferringVeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.VeterinaryClinic", "VeterinaryClinic")
                        .WithMany()
                        .HasForeignKey("VeterinaryClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Reception");

                    b.Navigation("ReferringVeterinarian");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("SubmittedByUser");

                    b.Navigation("VeterinaryClinic");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Reception");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Cremation", b =>
                {
                    b.Navigation("PaymentAccount");
                });

            modelBuilder.Entity("pcms.Domain.Entities.CremationPackage", b =>
                {
                    b.Navigation("Cremations");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("pcms.Domain.Entities.PaymentAccount", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Reception", b =>
                {
                    b.Navigation("Cremation");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Urn", b =>
                {
                    b.Navigation("Cremations");
                });

            modelBuilder.Entity("pcms.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Veterinarian", b =>
                {
                    b.Navigation("ReferredReceptions");
                });

            modelBuilder.Entity("pcms.Domain.Entities.VeterinaryClinic", b =>
                {
                    b.Navigation("ReferredReceptions");

                    b.Navigation("Veterinarians");
                });
#pragma warning restore 612, 618
        }
    }
}
