// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pcms.Infrastructure.Persistence;

#nullable disable

namespace pcms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pcms.Domain.Entities.Cremation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("AsignadoAUsuarioId");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFinalizacion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("CremationType")
                        .HasColumnType("integer")
                        .HasColumnName("TipoCremacion");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaEntrega");

                    b.Property<bool>("IncludesCertificate")
                        .HasColumnType("boolean")
                        .HasColumnName("IncluyeCertificado");

                    b.Property<bool>("IncludesPawPrint")
                        .HasColumnType("boolean")
                        .HasColumnName("IncluyeHuella");

                    b.Property<bool>("IncludesUrn")
                        .HasColumnType("boolean")
                        .HasColumnName("IncluyeUrna");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Notas");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NombrePaquete");

                    b.Property<DateTime?>("ReadyForDeliveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaListaParaEntrega");

                    b.Property<Guid>("ReceptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecepcionId");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaProgramada");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("InstruccionesEspeciales");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInicio");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Estado");

                    b.Property<string>("UrnDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DescripcionUrna");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ReceptionId")
                        .IsUnique();

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.ToTable("Cremaciones", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CorreoElectronico");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Apellido");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("EdadAnios");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Raza");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfDeath")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFallecimiento");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Sexo");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Especie");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("PesoKg");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Mascotas", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Reception", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<bool>("HasPersonalBelongings")
                        .HasColumnType("boolean")
                        .HasColumnName("TieneObjetosPersonales");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Notas");

                    b.Property<string>("PersonalBelongingsDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DescripcionObjetosPersonales");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("MascotaId");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CodigoQr");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRecepcion");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecibidoPorUsuarioId");

                    b.Property<string>("ReferralNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("NotasReferencia");

                    b.Property<Guid?>("ReferringVeterinarianId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinarioReferenteId");

                    b.Property<decimal>("VerifiedWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PesoVerificadoKg");

                    b.Property<Guid?>("VeterinaryClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinariaId");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("ReferringVeterinarianId");

                    b.HasIndex("VeterinaryClinicId");

                    b.ToTable("Recepciones", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.ReceptionPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TipoContenido");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Notas");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("NombreArchivoOriginal");

                    b.Property<int>("PhotoType")
                        .HasColumnType("integer")
                        .HasColumnName("TipoFoto");

                    b.Property<Guid>("ReceptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecepcionId");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("RutaAlmacenamiento");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("NombreArchivoGuardado");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaSubida");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("SubidoPorUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("FotosRecepcion", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Usuario"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Finanzas"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Ventas"
                        });
                });

            modelBuilder.Entity("pcms.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CorreoElectronico");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Apellido");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("HashContrasena");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Veterinarian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Telefono");

                    b.Property<string>("ProfessionalLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CedulaProfesional");

                    b.Property<Guid>("VeterinaryClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("VeterinariaId");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ProfessionalLicenseNumber");

                    b.HasIndex("VeterinaryClinicId");

                    b.ToTable("Veterinarios", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.VeterinaryClinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Direccion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Telefono");

                    b.Property<string>("PrimaryContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NombreContactoPrincipal");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Name");

                    b.ToTable("Veterinarias", (string)null);
                });

            modelBuilder.Entity("pcms.Domain.Entities.Cremation", b =>
                {
                    b.HasOne("pcms.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.Reception", "Reception")
                        .WithOne("Cremation")
                        .HasForeignKey("pcms.Domain.Entities.Cremation", "ReceptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Pet", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Customer", "Customer")
                        .WithMany("Pets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Reception", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Pet", "Pet")
                        .WithOne("Reception")
                        .HasForeignKey("pcms.Domain.Entities.Reception", "PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.Veterinarian", "ReferringVeterinarian")
                        .WithMany("ReferredReceptions")
                        .HasForeignKey("ReferringVeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pcms.Domain.Entities.VeterinaryClinic", "VeterinaryClinic")
                        .WithMany("ReferredReceptions")
                        .HasForeignKey("VeterinaryClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pet");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("ReferringVeterinarian");

                    b.Navigation("VeterinaryClinic");
                });

            modelBuilder.Entity("pcms.Domain.Entities.ReceptionPhoto", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Reception", "Reception")
                        .WithMany("Photos")
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reception");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("pcms.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("pcms.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pcms.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Veterinarian", b =>
                {
                    b.HasOne("pcms.Domain.Entities.VeterinaryClinic", "VeterinaryClinic")
                        .WithMany("Veterinarians")
                        .HasForeignKey("VeterinaryClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VeterinaryClinic");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Reception");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Reception", b =>
                {
                    b.Navigation("Cremation");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("pcms.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("pcms.Domain.Entities.Veterinarian", b =>
                {
                    b.Navigation("ReferredReceptions");
                });

            modelBuilder.Entity("pcms.Domain.Entities.VeterinaryClinic", b =>
                {
                    b.Navigation("ReferredReceptions");

                    b.Navigation("Veterinarians");
                });
#pragma warning restore 612, 618
        }
    }
}
