using Microsoft.EntityFrameworkCore; using pcms.Application.Supplies.DTOs; using pcms.Application.Supplies.Interfaces; using pcms.Domain.Entities; using pcms.Infrastructure.Persistence;
namespace pcms.Infrastructure.Services;
public class ExpenseService(AppDbContext db):IExpenseService
{
 public async Task<ExpenseCategoryDto>CreateCategoryAsync(ExpenseCategoryInput i){SupplyValidation.Required(i.Name,"El nombre de la categoría");if(await db.ExpenseCategories.AnyAsync(x=>x.Name.ToLower()==i.Name.Trim().ToLower()))throw new InvalidOperationException("La categoría ya existe.");var x=new ExpenseCategory{Id=Guid.NewGuid(),Name=i.Name.Trim(),Description=SupplyValidation.Optional(i.Description),CreatedAt=DateTime.UtcNow};db.ExpenseCategories.Add(x);await db.SaveChangesAsync();return new(x.Id,x.Name,x.Description,x.IsActive,x.CreatedAt,x.UpdatedAt);}
 public async Task<IEnumerable<ExpenseCategoryDto>>GetCategoriesAsync(bool active)=>await db.ExpenseCategories.AsNoTracking().Where(x=>x.IsActive==active).OrderBy(x=>x.Name).Select(x=>new ExpenseCategoryDto(x.Id,x.Name,x.Description,x.IsActive,x.CreatedAt,x.UpdatedAt)).ToListAsync();
 public async Task<ExpenseDto>CreateAsync(ExpenseInput i,Guid? userId){if(i.Subtotal<0||i.Tax<0)throw new ArgumentException("Subtotal e impuestos no pueden ser negativos.");if(string.IsNullOrWhiteSpace(i.Description))throw new ArgumentException("La descripción es obligatoria.");if(string.IsNullOrWhiteSpace(i.Currency)||i.Currency.Trim().Length!=3)throw new ArgumentException("La moneda debe tener tres letras.");var cat=await db.ExpenseCategories.FirstOrDefaultAsync(x=>x.Id==i.ExpenseCategoryId&&x.IsActive);if(cat is null)throw new ArgumentException("La categoría no existe o está inactiva.");if(i.SupplierId.HasValue&&!await db.Suppliers.AnyAsync(x=>x.Id==i.SupplierId&&x.IsActive))throw new ArgumentException("El proveedor no existe o está inactivo.");var x=new Expense{Id=Guid.NewGuid(),ExpenseCategoryId=i.ExpenseCategoryId,SupplierId=i.SupplierId,ExpenseDate=i.ExpenseDate==default?DateTime.UtcNow.Date:i.ExpenseDate.Date,Description=i.Description.Trim(),Subtotal=decimal.Round(i.Subtotal,2),Tax=decimal.Round(i.Tax,2),Total=decimal.Round(i.Subtotal+i.Tax,2),Currency=i.Currency.Trim().ToUpperInvariant(),InvoiceReference=SupplyValidation.Optional(i.InvoiceReference),Notes=SupplyValidation.Optional(i.Notes),RecordedByUserId=userId,CreatedAt=DateTime.UtcNow};db.Expenses.Add(x);await db.SaveChangesAsync();await db.Entry(x).Reference(x=>x.ExpenseCategory).LoadAsync();if(x.SupplierId.HasValue)await db.Entry(x).Reference(x=>x.Supplier).LoadAsync();return Map(x);}
 public async Task<PagedExpensesDto>GetAllAsync(int page,int pageSize,DateTime?from,DateTime?to,Guid?categoryId,Guid?supplierId,bool active){page=SupplyValidation.Page(page);pageSize=SupplyValidation.Size(pageSize);var q=db.Expenses.AsNoTracking().Include(x=>x.ExpenseCategory).Include(x=>x.Supplier).Where(x=>x.IsActive==active);if(from.HasValue)q=q.Where(x=>x.ExpenseDate>=from.Value.Date);if(to.HasValue)q=q.Where(x=>x.ExpenseDate<to.Value.Date.AddDays(1));if(categoryId.HasValue)q=q.Where(x=>x.ExpenseCategoryId==categoryId);if(supplierId.HasValue)q=q.Where(x=>x.SupplierId==supplierId);var total=await q.CountAsync();var items=await q.OrderByDescending(x=>x.ExpenseDate).ThenByDescending(x=>x.CreatedAt).Skip((page-1)*pageSize).Take(pageSize).ToListAsync();return new(items.Select(Map),page,pageSize,total,(int)Math.Ceiling(total/(double)pageSize));}
 public async Task<bool>VoidAsync(Guid id){var x=await db.Expenses.FirstOrDefaultAsync(x=>x.Id==id&&x.IsActive);if(x is null)return false;x.IsActive=false;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return true;}static ExpenseDto Map(Expense x)=>new(x.Id,x.ExpenseCategoryId,x.ExpenseCategory.Name,x.SupplierId,x.Supplier?.Name,x.ExpenseDate,x.Description,x.Subtotal,x.Tax,x.Total,x.Currency,x.InvoiceReference,x.Notes,x.RecordedByUserId,x.IsActive,x.CreatedAt,x.UpdatedAt);
}
