using Microsoft.EntityFrameworkCore;
using pcms.Application.Inventory;
using pcms.Application.Reporting;
using pcms.Domain.Enums;
using pcms.Infrastructure.Persistence;
namespace pcms.Infrastructure.Services;
public class InventoryReportService(AppDbContext db,IInventoryService inventory):IInventoryReportService
{
 public async Task<InventoryReportDto> GetAsync(DateTime? from,DateTime? to,string? search,SupplyInventoryMovementType? type){var now=DateTime.UtcNow.Date;var start=from?.Date??new DateTime(now.Year,now.Month,1);var end=to?.Date??now;if(end<start)throw new ArgumentException("La fecha final debe ser igual o posterior a la inicial.");var finish=end.AddDays(1);
  var current=(await inventory.GetCurrentAsync(search)).ToDictionary(x=>x.SupplyItemId);var supplies=await db.SupplyItems.AsNoTracking().Where(x=>current.Keys.Contains(x.Id)).Select(x=>new{x.Id,x.Category,x.ScanCode,x.IsActive}).ToListAsync();var stock=current.Values.Select(x=>{var s=supplies.First(y=>y.Id==x.SupplyItemId);return new InventoryStockReportDto(x.SupplyItemId,x.Name,s.Category,x.UnitOfMeasure,s.ScanCode,x.CurrentQuantity,x.MinimumQuantity,x.IsLowStock,s.IsActive);}).ToList();
  var movements=db.SupplyInventoryMovements.AsNoTracking().Where(x=>x.OccurredAt>=start&&x.OccurredAt<finish&&(!type.HasValue||x.MovementType==type));if(!string.IsNullOrWhiteSpace(search))movements=movements.Where(x=>x.SupplyItem.Name.Contains(search)||x.SupplyItem.ScanCode.Contains(search));var summary=(await movements.GroupBy(x=>x.MovementType).Select(g=>new{Type=g.Key,Quantity=g.Sum(x=>x.Quantity),Count=g.Count()}).ToListAsync()).Select(x=>new MovementSummaryDto(x.Type,x.Quantity,x.Count,Sign(x.Type)>0)).ToList();
  var lotBase=db.SupplyInventoryLots.AsNoTracking().Include(x=>x.SupplyItem).Where(x=>string.IsNullOrWhiteSpace(search)||x.ScanCode.Contains(search)||x.SupplyItem.Name.Contains(search));var lotEntities=await lotBase.ToListAsync();var lotIds=lotEntities.Select(x=>x.Id).ToArray();var lotMoves=await db.SupplyInventoryMovements.AsNoTracking().Where(x=>x.SupplyInventoryLotId.HasValue&&lotIds.Contains(x.SupplyInventoryLotId.Value)).Select(x=>new{x.SupplyInventoryLotId,x.MovementType,x.Quantity}).ToListAsync();var lots=lotEntities.Select(x=>{var remaining=x.InitialQuantity+lotMoves.Where(m=>m.SupplyInventoryLotId==x.Id).Sum(m=>Sign(m.MovementType)*m.Quantity);return new LotReportDto(x.Id,x.SupplyItem.Name,x.ScanCode,x.ManufacturerLotNumber,x.InitialQuantity,remaining,x.UnitOfMeasure,x.ReceivedAt,x.IsActive,remaining<=0,remaining>0&&remaining<=x.InitialQuantity*.1m);}).ToList();
  var productions=await db.ManufacturedUrnProductions.AsNoTracking().Include(x=>x.Urn).Include(x=>x.UrnBillOfMaterials).Include(x=>x.MaterialUsages).Where(x=>x.ProducedAt>=start&&x.ProducedAt<finish).Select(x=>new ProductionReportDto(x.Id,x.Urn.Name,x.UrnBillOfMaterials.Version,x.QuantityProduced,x.ProducedAt,x.MaterialUsages.Select(u=>new ProductionVarianceDto(u.SupplyItemNameSnapshot,u.ExpectedQuantity,u.ActualQuantity,u.WasteQuantity,u.UnitOfMeasure,u.ActualQuantity-u.ExpectedQuantity)).ToList())).ToListAsync();
  var mappings=await db.UrnSupplyItems.AsNoTracking().Where(x=>x.IsActive).Include(x=>x.Urn).Include(x=>x.SupplyItem).ToListAsync();var ids=mappings.Select(x=>x.SupplyItemId).ToArray();var finishedMoves=await db.SupplyInventoryMovements.AsNoTracking().Where(x=>ids.Contains(x.SupplyItemId)).ToListAsync();var finished=mappings.Select(x=>{var q=finishedMoves.Where(m=>m.SupplyItemId==x.SupplyItemId);var quantity=q.Sum(m=>Sign(m.MovementType)*m.Quantity);return new FinishedUrnStockDto(x.Urn.Name,x.SupplyItem.Name,quantity,x.SupplyItem.MinimumQuantity,quantity<=x.SupplyItem.MinimumQuantity,q.Where(m=>m.MovementType==SupplyInventoryMovementType.PurchaseReceipt).Sum(m=>m.Quantity),q.Where(m=>m.MovementType==SupplyInventoryMovementType.ManufacturingReceipt).Sum(m=>m.Quantity));}).ToList();return new InventoryReportDto(start,end,stock,summary,lots,productions,finished);}
 static int Sign(SupplyInventoryMovementType t)=>t is SupplyInventoryMovementType.ManualAdjustmentDecrease or SupplyInventoryMovementType.Consumption or SupplyInventoryMovementType.Waste or SupplyInventoryMovementType.PurchaseReturn or SupplyInventoryMovementType.ManufacturingConsumption?-1:1;
}
