using Microsoft.EntityFrameworkCore;
using pcms.Application.Supplies.DTOs;
using pcms.Application.Supplies.Interfaces;
using pcms.Domain.Entities;
using pcms.Infrastructure.Persistence;

namespace pcms.Infrastructure.Services;

internal static class SupplyValidation { public static string? Optional(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim(); public static void Required(string value, string label) { if (string.IsNullOrWhiteSpace(value)) throw new ArgumentException($"{label} es obligatorio."); } public static int Page(int value) => value < 1 ? 1 : value; public static int Size(int value) => Math.Clamp(value, 1, 100); }

public class SupplierService(AppDbContext db) : ISupplierService
{
    public async Task<SupplierDto> CreateAsync(SupplierInput i) { Validate(i); var x = new Supplier { Id=Guid.NewGuid(), Name=i.Name.Trim(), LegalName=SupplyValidation.Optional(i.LegalName), TaxId=SupplyValidation.Optional(i.TaxId), ContactName=SupplyValidation.Optional(i.ContactName), Phone=SupplyValidation.Optional(i.Phone), Email=SupplyValidation.Optional(i.Email), Website=SupplyValidation.Optional(i.Website), Address=SupplyValidation.Optional(i.Address), Notes=SupplyValidation.Optional(i.Notes), CreatedAt=DateTime.UtcNow }; db.Suppliers.Add(x); await db.SaveChangesAsync(); return Map(x); }
    public async Task<PagedSuppliersDto> GetAllAsync(int page,int pageSize,string? search,bool active) { page=SupplyValidation.Page(page); pageSize=SupplyValidation.Size(pageSize); var q=db.Suppliers.AsNoTracking().Where(x=>x.IsActive==active); if(!string.IsNullOrWhiteSpace(search)){var s=search.Trim().ToLower();q=q.Where(x=>x.Name.ToLower().Contains(s)||(x.TaxId!=null&&x.TaxId.ToLower().Contains(s)));} var total=await q.CountAsync();var items=await q.OrderBy(x=>x.Name).Skip((page-1)*pageSize).Take(pageSize).ToListAsync();return new(items.Select(Map),page,pageSize,total,(int)Math.Ceiling(total/(double)pageSize)); }
    public async Task<SupplierDto?> GetByIdAsync(Guid id)=>MapNullable(await db.Suppliers.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id));
    public async Task<SupplierDto?> UpdateAsync(Guid id,SupplierInput i){var x=await db.Suppliers.FindAsync(id);if(x is null)return null;Validate(i);x.Name=i.Name.Trim();x.LegalName=SupplyValidation.Optional(i.LegalName);x.TaxId=SupplyValidation.Optional(i.TaxId);x.ContactName=SupplyValidation.Optional(i.ContactName);x.Phone=SupplyValidation.Optional(i.Phone);x.Email=SupplyValidation.Optional(i.Email);x.Website=SupplyValidation.Optional(i.Website);x.Address=SupplyValidation.Optional(i.Address);x.Notes=SupplyValidation.Optional(i.Notes);x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Map(x);}
    public Task<bool> DeactivateAsync(Guid id)=>SetActive(id,false); public Task<bool> RestoreAsync(Guid id)=>SetActive(id,true); private async Task<bool>SetActive(Guid id,bool active){var x=await db.Suppliers.FirstOrDefaultAsync(x=>x.Id==id&&x.IsActive!=active);if(x is null)return false;x.IsActive=active;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return true;}
    static void Validate(SupplierInput i)=>SupplyValidation.Required(i.Name,"El nombre del proveedor"); static SupplierDto Map(Supplier x)=>new(x.Id,x.Name,x.LegalName,x.TaxId,x.ContactName,x.Phone,x.Email,x.Website,x.Address,x.Notes,x.IsActive,x.CreatedAt,x.UpdatedAt); static SupplierDto? MapNullable(Supplier? x)=>x is null?null:Map(x);
}

public class SupplyItemService(AppDbContext db) : ISupplyItemService
{
    public async Task<SupplyItemDto>CreateAsync(SupplyItemInput i){Validate(i);await EnsureScanCode(i.ScanCode,null);var x=new SupplyItem{Id=Guid.NewGuid(),Name=i.Name.Trim(),Description=SupplyValidation.Optional(i.Description),InternalSku=SupplyValidation.Optional(i.InternalSku),Category=i.Category.Trim(),UnitOfMeasure=i.UnitOfMeasure.Trim(),TrackInventory=i.TrackInventory,MinimumQuantity=i.MinimumQuantity,ScanCode=i.ScanCode.Trim(),CreatedAt=DateTime.UtcNow};db.SupplyItems.Add(x);await db.SaveChangesAsync();return Map(x);}
    public async Task<PagedSupplyItemsDto>GetAllAsync(int page,int pageSize,string?search,bool active){page=SupplyValidation.Page(page);pageSize=SupplyValidation.Size(pageSize);var q=db.SupplyItems.AsNoTracking().Where(x=>x.IsActive==active);if(!string.IsNullOrWhiteSpace(search)){var s=search.Trim().ToLower();q=q.Where(x=>x.Name.ToLower().Contains(s)||x.ScanCode.ToLower().Contains(s)||(x.InternalSku!=null&&x.InternalSku.ToLower().Contains(s)));}var total=await q.CountAsync();var items=await q.OrderBy(x=>x.Name).Skip((page-1)*pageSize).Take(pageSize).ToListAsync();return new(items.Select(Map),page,pageSize,total,(int)Math.Ceiling(total/(double)pageSize));}
    public async Task<SupplyItemDto?>GetByIdAsync(Guid id)=>MapNullable(await db.SupplyItems.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id)); public async Task<SupplyItemDto?>GetByScanCodeAsync(string code)=>MapNullable(await db.SupplyItems.AsNoTracking().FirstOrDefaultAsync(x=>x.ScanCode==code.Trim()&&x.IsActive));
    public async Task<SupplyItemDto?>UpdateAsync(Guid id,SupplyItemInput i){var x=await db.SupplyItems.FindAsync(id);if(x is null)return null;Validate(i);await EnsureScanCode(i.ScanCode,id);x.Name=i.Name.Trim();x.Description=SupplyValidation.Optional(i.Description);x.InternalSku=SupplyValidation.Optional(i.InternalSku);x.Category=i.Category.Trim();x.UnitOfMeasure=i.UnitOfMeasure.Trim();x.TrackInventory=i.TrackInventory;x.MinimumQuantity=i.MinimumQuantity;x.ScanCode=i.ScanCode.Trim();x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Map(x);}
    public Task<bool>DeactivateAsync(Guid id)=>SetActive(id,false);public Task<bool>RestoreAsync(Guid id)=>SetActive(id,true);private async Task<bool>SetActive(Guid id,bool active){var x=await db.SupplyItems.FirstOrDefaultAsync(x=>x.Id==id&&x.IsActive!=active);if(x is null)return false;x.IsActive=active;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return true;}private async Task EnsureScanCode(string code,Guid? id){SupplyValidation.Required(code,"El código de escaneo");if(await db.SupplyItems.AnyAsync(x=>x.ScanCode==code.Trim()&&x.Id!=id))throw new InvalidOperationException("El código de escaneo ya existe.");}static void Validate(SupplyItemInput i){SupplyValidation.Required(i.Name,"El nombre del insumo");SupplyValidation.Required(i.Category,"La categoría");SupplyValidation.Required(i.UnitOfMeasure,"La unidad de medida");if(i.MinimumQuantity<0)throw new ArgumentException("La cantidad mínima no puede ser negativa.");}static SupplyItemDto Map(SupplyItem x)=>new(x.Id,x.Name,x.Description,x.InternalSku,x.Category,x.UnitOfMeasure,x.TrackInventory,x.MinimumQuantity,x.ScanCode,x.IsActive,x.CreatedAt,x.UpdatedAt);static SupplyItemDto?MapNullable(SupplyItem?x)=>x is null?null:Map(x);
}
